baseURL = 'https://teja463.github.io/'
languageCode = 'en-us'
title = 'Teja Ponnuru'

paginate = 5

[params]
    myDateFormat = "Jan 2, 2006"
    description = "Brahma Teja Ponnuru"

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "authors"